---
# tasks file for sa-uwsgi

  - include_tasks: __detect_init_system.yml
    when: upstart_system is not defined

  - include_tasks: tasks_python.yml
    when: option_install_python

  - include_tasks: tasks_python3.yml
    when: option_install_python3


  - include_tasks: tasks_uwsgi.yml
